diff -Nurp ./cardiod1.html ../tthtlc.github.io_old/cardiod1.html
diff -Nurp ./cardiod_line.html ../tthtlc.github.io_old/cardiod_line.html
diff -Nurp ./double_square1.html ../tthtlc.github.io_old/double_square1.html
diff -Nurp ./double_square1.js ../tthtlc.github.io_old/double_square1.js
diff -Nurp ./enneper.html ../tthtlc.github.io_old/enneper.html
diff -Nurp ./enneper_rotating1.html ../tthtlc.github.io_old/enneper_rotating1.html
diff -Nurp ./enneper_rotating.html ../tthtlc.github.io_old/enneper_rotating.html
diff -Nurp ./generalized_drawing_board.html ../tthtlc.github.io_old/generalized_drawing_board.html
diff -Nurp ./generalized.html ../tthtlc.github.io_old/generalized.html
diff -Nurp ./icosahedron_labelled.html ../tthtlc.github.io_old/icosahedron_labelled.html
diff -Nurp ./pythogarean_tree1.html ../tthtlc.github.io_old/pythogarean_tree1.html
diff -Nurp ./pythogarean_tree2.html ../tthtlc.github.io_old/pythogarean_tree2.html
diff -Nurp ./pythogarean_tree.html ../tthtlc.github.io_old/pythogarean_tree.html
diff -Nurp ./pythoras.html ../tthtlc.github.io_old/pythoras.html
diff -Nurp ./pythoras_tree.html ../tthtlc.github.io_old/pythoras_tree.html
diff -Nurp ./recursive_fractal2.html ../tthtlc.github.io_old/recursive_fractal2.html
diff -Nurp ./truncated_dodecahedron2.html ../tthtlc.github.io_old/truncated_dodecahedron2.html
diff -Nurp ./truncated_dodecahedron3.html ../tthtlc.github.io_old/truncated_dodecahedron3.html
diff -Nurp ./truncated_dodecahedron4.html ../tthtlc.github.io_old/truncated_dodecahedron4.html
diff -Nurp ./truncated_dodecahedron_one_corner.html ../tthtlc.github.io_old/truncated_dodecahedron_one_corner.html
diff -Nurp ./webgl_3d_ellipsoid.html ../tthtlc.github.io_old/webgl_3d_ellipsoid.html
